### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by EdgeLab-FHDO** [EdgeLab-FHDO/Edge-Diagnostic-Platform#1]
Decide which file structure should be used.

**Comment by alyhasansakr** [comment]
and create folders as required.

**Comment by alyhasansakr** [comment]
as mentioned in #2 , the build tool for the infrastructure manager is Gradle, the file structure should be built accordingly.

**Comment by juan-castrillon** [comment]
So, after doing some research, and the way I understand [this](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html) , [this](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_project_layout) and [this](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:compile), the main convention is to have a src folder with main/java/ for the "production" code, and test/java/ for the test code. However, it seems like the project layout can be easily [customized](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:compile) using the build.gradle file.

So, my suggestion would be to start with a layout like the following, and then if necesarry customize the build:
![Example Layout](https://lh3.googleusercontent.com/proxy/Aw-v-d55rF7PfUSRMbjAcNL-sFII26ovbAut2ITgs3LpDUs8rSAbdYrCTo8gfKt8K5oyl1usb6autvKghWT661vILPcnQx6gXf53ol8kfuKObLtc45WUWgbk4wHb)

Also, I think its worth noting that IntelliJ IDE, provides the option to create a new gradle project and when I tried it, it generated the following:

![File structure generated by IntelliJ](https://i.imgur.com/9CUIzzI.png)

**Comment by alyhasansakr** [comment]
ok, good structure, create a pull request for it.
