### ISSUE TITLE
Undesired GET Output Behaviour

### ISSUE THREAD

**Issue by juan-castrillon** [EdgeLab-FHDO/Edge-Diagnostic-Platform#105]
While developing the Diagnostics App i noticed that In the current state of the platform, GEToutputs have an undesired behavior.

If a request is made before the resource is created (but still on a valid URI), instead of returning "" like before, it returns a 404 page. 

This will for example break the limit bash file (It assumes the master answers with "" before sending a limit). So in order for it to work, the limit assingment would have to be done before the limit script is running in the remote machine. 

After inspecting, the cause is that GET outputs only get activated when they are passed a resource for the first time, which in my opinion is a bug. Activating them just after starting the server makes more sense and requires almost no changes to the code.

I can do the modifications and make a pull request, but first I wanted some opinions in whether this is the way we want the platform to behave or not @alyhasansakr

**Comment by alyhasansakr** [comment]
@juan-castrillon yes, go ahead and make the changes.
