### ISSUE TITLE
Simple Main With Test

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#11]
Write a simple main function and a corresponding test function, a function that returns Hello World is enough.
Then create an action in GitHub to do the test automatically.

**Comment by juan-castrillon** [comment]
When reading about Github actions, I come across the option to publish the resulting built packages into GitHub Packages or Maven Central Repository (see [here](https://docs.github.com/en/actions/publishing-packages-with-github-actions/about-packaging-with-github-actions)). I would say, is not necessary right now, but what do you think?

**Comment by alyhasansakr** [comment]
Not important for the infrastructure manager, we are only interested in tests

**Comment by alyhasansakr** [comment]
We should be able to see test results when a pull-request is made here, @juan-castrillon go ahead and make one with a test.
