### ISSUE TITLE
The Master Class

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#15]
The Master class is the main entry point of our back-end.
The Master has two streams; input and output. For example, providing "deploy application" in the input gives "Helm chart execution" output, here the master should not execute the Helm chart on its own, instead, it just sends a message for Helm controller (another application).
The Master also has the configuration of the platform, which should be written in an extensible format (JSON/XML) and read from a file.
The Master is our default place for any function that we don't know yet where it should be. We have to refactor it regulatory to make sure it doesn't get out of control.

As we still don't know how most of the other functionalities look like, what is required here is to just write a simple class that can do the functionality mentioned above (output is just printing for now), including tests of course.
Create other classes as necessary, you can look at the class diagram in #3 but you can also just write your own.

This is our first piece of code, so there will be a lot of modifications and discussions. We still don't have code rules, we are also going to develop that with this ticket. @theodorelu27 should also join the discussions once we have a pull-request.

**Comment by juan-castrillon** [comment]
There is a couple of things not very clear to me if you could help me figure it out so I can start it would be great : 

1. The way i understand it, for the outputs, I should base myself on the initial component diagram and "model" the interfaces between the IM and the other controllers (HELM, GUI, Logger, Application and Node). Is that correct?
2. What do you mean by " configuration of the platform" ? 

Thanks in advance!

**Comment by alyhasansakr** [comment]
This is exactly the type of information that we don't have now.
What we need to do here is something abstract, and we need to do it in a way that is easy to extend.
So what you need to do here is only input and output for console, which should be easily replaceable by other inputs and outputs.
And this is where configuration comes in, the first things we need to specify in the configuration are inputs and outputs, other parameters will come in eventually, so this one also needs to be easily extensible.
