### ISSUE TITLE
Implemented Class Diagram

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#18]
Now that we have implemented the first group of classes, it makes sense to create a class diagram of what is actually implemented. It should contain the following:
1. Class name.
1. Class attributes with type and visibility.
1. Class Methods with parameters and visibility.
1. Relations between classes, mainly inheritance and coupling.

The new class diagram should be included in the wiki, and mark the old version as "Draft".

**Comment by juan-castrillon** [comment]
Here is an initial sketch, showing what we have in the master branch so far. If you consider it accurate, I will close this issue and upload it to the wiki. 

![Class_Diagram](https://user-images.githubusercontent.com/64461123/90245122-59876d00-de32-11ea-85c0-d37481e05d0a.png)

**Comment by alyhasansakr** [comment]
Yes, that is accurate, upload to wiki and close the issue.
