### ISSUE TITLE
Other Similar Diagnostics Tools

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#19]
Search for other diagnostics tools or platforms that already exist in the Internet. Then we would like to study how they work and get inspirations out of them.

**Comment by theodorelu27** [comment]
So far I only found these candidates, I tried to focus on solutions/studies that offers some kind of monitoring for an IT/IoT System, I'd update the list as research goes

- DynaTrace
resource: https://www.dynatrace.com/
TL;dr : DynaTrace is an AI-powered SaaS for digital business analytics which includes failure analaysis
related study: 
https://dl.acm.org/doi/pdf/10.1145/2668930.2688061 - the researchers proposes to use DynaTrace's application performance management analysis to automatically generate a performance model to avoid over-provision

- Splunk
resource: https://www.splunk.com/en_us/iot/preventative-maintenance-and-predictive-analytics.html
Monitor and Diagnose performance, as well as predict failures

**Comment by alyhasansakr** [comment]
That's great, carry on.

**Comment by juan-castrillon** [comment]
You may wanna take a look at Zabbix which I think looks very promising 

![image](https://assets.zabbix.com/img/illustrations/metric_collection.svg)


See the [webpage](url) and the [documentation](url)

Its described as an integrated network monitoring solution, and allows network, server, cloud, application and services monitoring by metric collection.  Its also open-source (GNU-GPL v2) , which means the code is accesible if we wanted on [github](https://github.com/zabbix/zabbix) or [their own git repository](https://git.zabbix.com/projects/ZBX/repos/zabbix/browse)

**Comment by theodorelu27** [comment]
@juan-castrillon Thank you for the input, I believe it could be useful

I'd also like to propose some new candidates:
- Data Dog
resource: https://docs.datadoghq.com/getting_started/integrations/
resource monitoring tool, but the interesting part is their addition of API integration for established system that cannot have their agenst installed
- PRTG Network Monitor
resource: https://www.paessler.com/manuals/prtg/introduction
resource monitoring tool, they also check for quality of service, so might be a useful reference

btw would these references be enough as the deliverables of these issues or would it be better if I make some sort of short summaries for each? @alyhasansakr

**Comment by alyhasansakr** [comment]
Good job, that is enough, let me close the issue.
