### ISSUE TITLE
Cgroups Integration

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#30]
To limit CPU usage for edge nodes, we use Cgroups in a BASH script.

The script should be able to receive the name of an edge node (node-1 for example) and apply a defined CPU limit (1.5 cores for example). The main idea is that any running instance of an application should have the edge node name as part of the command that was used to start it, and thus is searchable.

Here is an [example](https://github.com/EdgeLab-FHDO/Edge-Diagnostic-Platform/files/5177819/limit.txt).

Don't forget to add automated tests.

**Comment by juan-castrillon** [comment]
Hey @alyhasansakr. So just to be clear and as i am new to BASH scripts, I want to have things clear from the beggining:

 - I understand that I should add another MasterOutput, who is capable of running a bash script, given a command from the master.  The bash script runs in a different machine than the master right? So and additional component should be developed to be deployed in the same machine as the bash script and listen for a command from the MasterOutput (via REST?).

 - The bash script to run, should accept the edge node as a parameter and use cgroups to limit its CPU. It can be based on the example you provide. 

 - The automated test, should be on the java developed components (Or the bashscript?)

Am I getting everything right?
