### ISSUE TITLE
Master Multi-output Separation

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#41]
Currently the configuration specifies the following independently:
- Which input connects to which output.
- Mapping between input commands and output commands.

The problem is the following: You may need to have a single input command that is mapped to two different output commands for two different outputs.

Currently this is possible by just adding the two different mappings, however, this means that both outputs are going to receive ALL output commands, which includes output commands that are not defined for them.

For example, you have a single event that should limit both bandwidth and CPU, but bandwidth output is different than CPU output. Using what we have now, bandwidth output commands have to go to CPU output as well, which throws an exception.

Possible solution: The configuration should specify input, output and command mapping in the same rule.

For example, rules that map event input (from scenario S1) to bandwidth limiter (BL1) and CPU limiter (CL1) should look like the following:
```JSON
{
   "rules":
   [
      {
         "input": "S1",
         "output": "BL1",
         "inputCommand": "applyLimits $bandwidth_limit $CPU_limit",
         "outputCommand": "advantEdge networkUpdate sandbox_1 edge_1 EDGE $bandwidth_limit $bandwidth_limit 2 1 0.001"
      },
      {
         "input": "S1",
         "output": "CL1",
         "inputCommand": "applyLimits $bandwidth_limit $CPU_limit",
         "outputCommand": "limit edge_1 $CPU_limit 100000"
      }
   ]
}
```

For that to work correctly, we need to define inputs and outputs in the configuration file (like "rest": "CL1").

You can also notice that there is one more requirement here: Parameters mapping. Commands have parameters which needs to be mapped as well. My suggestion is to use the symbol $ to indicate that whatever comes here in the input command is copied to the corresponding one in the output command. For that I don't want to implement a pattern matching functionality to extract the parameter values from the input, instead just enforce a rule for separation using spaces (as we already have), which means that the following is not a valid input command "applyLimits ($bandwidth_limit,$CPU_limit)" since it doesn't separate with spaces. This rule is not enforced for the output command replacement, because it is just a trivial find and replace function.

**Comment by juan-castrillon** [comment]
I have a couple of questions and want to clarify everything before getting on this issue:

The requirements are:

- Configuration of the master should allow to specify for a given input command (e.g applyLimits) a mapping to not only one (like currently) but more outputs.

- Parameters that are mapped from input command to output command, should also be specified in the configuration file, (possibly by using placeholders [$] ) and space separation needs to be present in order for an input command to be valid

The question I have is:

- The rule suggestion you make, will it replace the runners? Its not quite clear to me why to relate the different inputs and outputs wiht the commands. Because, according to the requirements, I can think of a way to only replace the commands in the config file by JSON objects, for example : 

```json
"commands" : [
    {
      "input" : "applyLimits $bw_limit $cpu_limit",
      "mappings" : [ 
        "advantEdge networkUpdate sandbox_1 edge_1 EDGE $bandwidth_limit $bandwidth_limit 2 1 0.001", 
        "limit edge_1 $CPU_limit 100000"
      ]
    }
  ]
```
This way, we leave the threaded runner functionality like it is and we enable that no matter the MasterInput that calls the command (applyLimits in this case), the mapping would be the same, while not having to repeat the config for every I/O combination. What do you think @alyhasansakr ?

**Comment by alyhasansakr** [comment]
@juan-castrillon 
How to specify that the first command goes to advantedge and the second command goes to rest controller? And what happens if you have more than one output of the same type for the same input? And what if you have two inputs that sends the same command but you want them to go to different outputs?

It is not just a command mapping, it must also indicate which runner is the input and which ones are the outputs. And for that we need to identify different instances of inputs and outputs in the configuration file (we already create them for the runner in the code). That is why I used the names S1, BL1, and so on. We may need to add an ID attribute for each input and output in the configuration file.

If you don't want to repeat input/output combinations (more readable and easier to change), then make a definition for input/output combinations in the configuration file (as identifiers), and refer to them in each command. This part is an additional development effort that we may not necessarily need right now, it is up to you if you wish to do.

**Comment by juan-castrillon** [comment]
Based on what I understand about this issue, i've sketched a configuration file. Once we agree on the config file design, I can start implementing the code to work with it: 
```json
{
  "ioData": {
      "inputs": [
        {"type": "ConsoleInput","name": "console_in"},
        {"type": "RestInput","name": "rest_in"},
        {"type": "MatchMaker","name": "match_m"}
      ],
      "outputs": [
        {"type": "ConsoleOutput","name": "console_out"},
        {"type": "RestOutput","name": "rest_out"},
        {"type": "MasterUtility","name": "util"},
        {"type": "AdvantEdgeClient","name": "advant_e","port" : 10500},
        {"type": "ScenarioDispatcher","name": "scenario_dispatcher"},
        {"type": "ScenarioEditor","name": "scenario_editor"},
        {"type": "MatchMaker","name": "match_m"}
      ]
    },
  "connections" : [
    {
      "name" : "c1",
      "in" : "console_in",
      "out" : "console_out",
      "commands" : {
        "deploy_application" : "console helmChartExecution" ,
        "update_gui" : "console GUIUpdateExecution" ,
        "node_request" : "console matchMakingExecution" ,
        "save_statistics" : "console LoggerExecution" ,
        "show_statistics" : "console GUIUpdateExecution"
      }
    },
    {
      "name" : "c2",
      "in" : "console_in",
      "out" : "util",
      "commands" : {
        "exit" : "util exit",
        "start_rest_server" : "util runRunner RestServer",
        "start_runner" : "util runRunner"
      }
    },
    {
      "name" : "c3",
      "in" : "console_in",
      "out" : "advant_e",
      "commands" : {
        "ae_create_scenario" : "advantEdge create",
        "ae_deploy_scenario" : "advantEdge deploy",
        "ae_terminate_active" : "advantEdge terminate"
      }
    },
    {
      "name" : "c4",
      "in" : "console_in",
      "out" : "scenario_editor",
      "commands" : {
        "create_scenario" : "editor create",
        "add_event" : "editor addEvent",
        "delete_event" : "editor deleteEvent",
        "save_scenario" : "editor toFile",
        "read_scenario" : "editor fromFile"
      }
    },
    {
      "name" : "c5",
      "in" : "console_in",
      "out" : "scenario_dispatcher",
      "commands" : {
        "load_scenario" : "dispatcher fromFile",
        "run_scenario" : "dispatcher run",
        "pause_scenario" : "dispatcher pause",
        "resume_scenario" : "dispatcher resume"
      }
    },
    {
      "name" : "c6",
      "in" : "rest_in",
      "out" : "util",
      "commands" : {
        "exit" : "util exit",
        "start_runner" : "util runRunner"
      }
    },
    {
      "name" : "c7",
      "in" : "rest_in",
      "out" : "match_m",
      "commands" : {
        "register_client" : "matchMaker register_client",
        "register_node" : "matchMaker register_node",
        "assign_client" : "matchMaker assign_client"
      }
    },
    {
      "name" : "c8",
      "in" : "match_m",
      "out" : "rest_out",
      "commands" : {
        "give_node": "restOut sendNode"
      }
    },
    {
      "name" : "c9",
      "in" : "console_in",
      "out" : "rest_out",
      "commands" : {
        "limit_node" : "restOut limit"
      }
    }
  ],
  "runners" : [
    {
      "name" : "Main",
      "scenario" : false,
      "connections" : ["c1","c2","c3","c4","c5","c9"]
    },
    {
      "name" : "RestInputTest",
      "scenario" : false,
      "connections" : ["c6","c7"]
    },
    {
      "name" : "MMInputTest",
      "scenario" : false,
      "connections" : ["c8"]
    },
    {
      "name" : "Dummy Scenario",
      "scenario" : true,
      "input" : "dummy",
      "outputs" : ["console_out"]
    }
  ],
  "RESTServer" : 4567
}
```
In this file:
- Relation between input and output instances are shown in "connections" where each connection show the relation of an input instance with an output instance and the commands from the input that will be redirected to that output (Parameter mapping is not included yet).
- The runners simply implement a given set of connections (therefore defining their inputs and outputs and the internal mapping of commands)
- I took the rest server definition out of the runners (Makes it more easy to configure instead of leaving empty fields)
- Note that the scenario is not modified as I believe once we agree on a structure for the other runners, the scenario (and the scenario json file) can be modified accordingly.

Let me know what you think @alyhasansakr

**Comment by alyhasansakr** [comment]
@juan-castrillon 
What information does a runner add? I say we totally remove runners from the configuration file, and put any other important information (REST server, scenario name, ..) as a parameter for the input. This way we always create a single runner for each input.

**Comment by juan-castrillon** [comment]
@alyhasansakr About the runners, I would say they have two functionalities:
- They provide a way of having more than one connection in a thread but if you say we create a runner/input that is already covered
- Provide a way of defining a main thread, which we can also do without them by saying for example the runner with console input is the main one by default. 

So, after having accounted for your comment, the file would look like this:
```json
{
  "ioData": {
      "inputs": [
        {"type": "ConsoleInput","name": "console_in"},
        {"type": "RestInput","name": "rest_in", "port": 4567},
        {"type": "MatchMaker","name": "match_m"},
        {"type": "Scenario", "name": "dummy"}
      ],
      "outputs": [
        {"type": "ConsoleOutput","name": "console_out"},
        {"type": "RestOutput","name": "rest_out"},
        {"type": "MasterUtility","name": "util"},
        {"type": "AdvantEdgeClient","name": "advant_e","port" : 10500},
        {"type": "ScenarioDispatcher","name": "scenario_dispatcher"},
        {"type": "ScenarioEditor","name": "scenario_editor"},
        {"type": "MatchMaker","name": "match_m"}
      ]
    },
  "connections" : [
    {
      "in" : "console_in",
      "out" : "console_out",
      "commands" : {
        "deploy_application" : "console helmChartExecution" ,
        "update_gui" : "console GUIUpdateExecution" ,
        "node_request" : "console matchMakingExecution" ,
        "save_statistics" : "console LoggerExecution" ,
        "show_statistics" : "console GUIUpdateExecution"
      }
    },
    {
      "in" : "console_in",
      "out" : "util",
      "commands" : {
        "exit" : "util exit",
        "start_rest_server" : "util runRunner RestServer",
        "start_runner" : "util runRunner"
      }
    },
    {
      "in" : "console_in",
      "out" : "advant_e",
      "commands" : {
        "ae_create_scenario" : "advantEdge create",
        "ae_deploy_scenario" : "advantEdge deploy",
        "ae_terminate_active" : "advantEdge terminate"
      }
    },
    {
      "in" : "console_in",
      "out" : "scenario_editor",
      "commands" : {
        "create_scenario" : "editor create",
        "add_event" : "editor addEvent",
        "delete_event" : "editor deleteEvent",
        "save_scenario" : "editor toFile",
        "read_scenario" : "editor fromFile"
      }
    },
    {
      "in" : "console_in",
      "out" : "scenario_dispatcher",
      "commands" : {
        "load_scenario" : "dispatcher fromFile",
        "run_scenario" : "dispatcher run",
        "pause_scenario" : "dispatcher pause",
        "resume_scenario" : "dispatcher resume"
      }
    },
    {
      "in" : "rest_in",
      "out" : "util",
      "commands" : {
        "exit" : "util exit",
        "start_runner" : "util runRunner"
      }
    },
    {
      "in" : "rest_in",
      "out" : "match_m",
      "commands" : {
        "register_client" : "matchMaker register_client",
        "register_node" : "matchMaker register_node",
        "assign_client" : "matchMaker assign_client"
      }
    },
    {
      "in" : "match_m",
      "out" : "rest_out",
      "commands" : {
        "give_node": "restOut sendNode"
      }
    },
    {
      "in" : "console_in",
      "out" : "rest_out",
      "commands" : {
        "limit_node" : "restOut limit"
      }
    },
    {
      "in" : "dummy",
      "out" : "console_out",
      "commands" : {
        "deploy_application" : "console helmChartExecution" ,
        "update_gui" : "console GUIUpdateExecution" ,
        "node_request" : "console matchMakingExecution"
      }
    }
  ]
}
```
Note that although scenarios are not tecnically an input (Events are) i defined them in the inputs, and will process that on code. I also added the rest port to the rest input definition.

Is it ok?

**Comment by alyhasansakr** [comment]
Yes, that is very good, go on with the implementation.
