### ISSUE TITLE
ConsoleInput, IN.nextLine() Issue

### ISSUE THREAD

**Issue by JeanValjean17** [EdgeLab-FHDO/Edge-Diagnostic-Platform#44]
There seems to be a problem with the ConsoleInput class, in the read method.

` public String read() {
        //
        System.out.println("Input >");
        return IN.nextLine();
    }`

In `return.IN.nextLine()` the console is not waiting for user input provoking a NoSuchElementException("No line found") exception. I tried this code in a separate simple application test and it works as intended. 

Do any of you have any idea what might be happening here? Solutions like the one [here](https://stackoverflow.com/questions/7877529/java-string-scanner-input-does-not-wait-for-info-moves-directly-to-next-stateme?rq=1) or using System.console() or BufferReader don't work either.

**Comment by alyhasansakr** [comment]
Up to this point we were just running the main directly (technically without Gradle), turns out in order to use console input (System.in) you must tell Gradle to connect it before hand.

I have a fix in the linked pull-request.
