### ISSUE TITLE
limit.sh -- sudo cgclassify -g cpu:/ -- SPID is not valid pid

### ISSUE THREAD

**Issue by JeanValjean17** [EdgeLab-FHDO/Edge-Diagnostic-Platform#47]
The limit script is receiving correctly from the input from the Rest Service in Master but is not applying the CPU limit on the application, here is a snippet from the output of the command, giving an error in the cgclassify:

[OutputCommand.txt](https://github.com/EdgeLab-FHDO/Edge-Diagnostic-Platform/files/5436090/OutputCommand.txt)

**Comment by alyhasansakr** [comment]
@juan-castrillon 
Could you debug limit.sh?

**Comment by alyhasansakr** [comment]
@JeanValjean17 It should be fixed now.
