### ISSUE TITLE
Runner Refactoring: Modules

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Edge-Diagnostic-Platform#69]
There is no new functionality needed here, it is just a better way to implement cases similar to match making, that is when you want to have more than a single input or output access the same instance.

To properly define that, we should not define inputs and outputs in the configuration file, instead, we define modules. Each module has a predefined set of inputs and outputs which can still be used the same way in connections (with added prefix to indicate which instance of the module is used). For example, we define a match making module with the name mm (and some parameters), then we can use mm.in as an input ("in" is a hard coded name) and mm.out as an output that will access the same instance. It may be that a single module has more than one input each with a unique name and functionality, but all of them access the same module instance.

This also help us defining namespaces and tests, as each module should have its own namespace (and folder) and set of tests.

Don't forget to write an abstract class Module and use it for each module we already have (console, rest, scenario, etc).

**Comment by juan-castrillon** [comment]
The way I understand this refactoring, Modules will be a "layer" of abstraction between the runners and the IOs, am I right?
If that is the case, I say, we have a runner (Thread) for each module, which in turn has inputs and outputs inside.

This can be seen in the model:
![abstract_model_v1](https://user-images.githubusercontent.com/64461123/101358766-9b359b00-389b-11eb-9d24-20443309f931.png)

So in that case, each module will have to implement the module interface (or abstract class in this case) and have hardcoded inputs and outputs.

We can even get rid of ScenarioRunners and have ScenarioModules with their own behaviour separate from the other modules.
![abstract_model_v2](https://user-images.githubusercontent.com/64461123/101359076-0d0de480-389c-11eb-8670-7f81b98a22f5.png)

What do you think @alyhasansakr ?

**Comment by alyhasansakr** [comment]
@juan-castrillon You got most of it right, these are my comments:

- Yes, one of the reason we do it this way is to make scenarios no longer special, it is now just a module (same for match-making).
- Inputs may block, and so each require its own thread, in our case that is the Runner. And in turn the position of the Module should be between the Master and MasterInput and MasterOutput. This is also important because some modules don't have inputs at all, and thus should not have a Runner.
- One of the other reasons we are doing this, is to not use a unified definition for EdgeClient and EdgeNode, each module will have its own definition of clients and nodes (if required). So remove them from this diagram.
- I believe configuration (and configurator and possibly configuration entry) should be a part of this diagram as well as connections.
- A Module is more an abstract class than an interface, in Java that translates into extends vs implements.

**Comment by juan-castrillon** [comment]
Ok, I will start working in the next version of the abstract model. However, I still think EdgeClient and EdgeNode should be in the master as well no? Isn't the master supposed to know (have a list) of registered clients and nodes? Maybe in this model, they can be shown without parameters or as interfaces or abstract classes?

**Comment by alyhasansakr** [comment]
different functions have different views of clients and nodes, some have even more definitions (application and point of access). What we did here liberates the master of any functionalities. So we don't need to worry about a complex inheritance tree.

**Comment by juan-castrillon** [comment]
Ok, here is my next iteration. I included the modules in the configuration and abstracted many things (Like the map for the commands) given that this should be an abstract and language independent model

![abstract_model_v2](https://user-images.githubusercontent.com/64461123/101474850-eeffbd00-394b-11eb-86fe-b6f1283dc1ef.png)

If this is a good model, I will add the modules and the different IOs below

**Comment by juan-castrillon** [comment]
After our discussion, I modifed what we agreed and also used multiplicity and relations to show attributes

![abstract_model_v3](https://user-images.githubusercontent.com/64461123/101789171-3ed3b500-3b01-11eb-9978-42c66f0675e5.png)

The big changes are:
- Master has modules instead of runners
- Modules are defined by having inputs, outputs and connections and have a way to start them
- Runners are part of the inputs
- An intermediate "getter" class, allows to get the response from a given command
- Command is now abstract (Without the strings)

Let me know what you think @alyhasansakr 😅

**Comment by alyhasansakr** [comment]
That is really good.

Next step here is to try to make the necessary changes to realize this model.

**Comment by juan-castrillon** [comment]
Now that we've defined modules as "containers" for inputs and outputs, my next step is to determine the modules needed for the design according to the requirements. I've come up with the following, what do you think @alyhasansakr ?

![modules](https://user-images.githubusercontent.com/64461123/102204477-321cdb80-3eca-11eb-9ee9-935648179cc9.png)

![ios](https://user-images.githubusercontent.com/64461123/102204533-3cd77080-3eca-11eb-8d9f-fe9636d4f3bb.png)

**Comment by juan-castrillon** [comment]
On a second tought, is REST abstract enough? Or would it be better to define it as an Abstract Communication Module?

**Comment by alyhasansakr** [comment]
I believe REST is abstract enough.

Why MatchMaker is still one class? One of the targets of using modules is to make this connection in the module itself rather than the inputs and outputs.

How is every ScenarioEvent an input running its own thread? that should be a ScenarioRunner.

**Comment by juan-castrillon** [comment]
I was thinking the same thing, for me makes more sense to define Scenario as MasterInput (instead of each event) and in the model specify a different kind of runner, like this:

![image](https://user-images.githubusercontent.com/64461123/102212831-1b7c8180-3ed6-11eb-8344-b52e752c4535.png)

This would translate in either of two options:
1. ScenarioModule for each scenario

![image](https://user-images.githubusercontent.com/64461123/102213234-b9704c00-3ed6-11eb-8bb3-5ae7c4e4e11f.png)

2. One scenarioModule that contains all declared scenarios
![image](https://user-images.githubusercontent.com/64461123/102213304-d573ed80-3ed6-11eb-8384-f894fe2542c9.png)

What do you think?

**Comment by alyhasansakr** [comment]
Option one is better, because we need one ScenarioModule for each Scenario.

But why do we still differentiate between a ScenarioRunner and any other Runner? All of the special requirements of a ScenarioRunner should be moved to the ScenarioModule.

**Comment by juan-castrillon** [comment]
Should I go ahead and start with this? Or are we waiting for some other issue?

**Comment by alyhasansakr** [comment]
Everything else is merged, but I still need to have a look throughout the whole code to make sure that our understanding is correct. I will let you know if and when you should start this (probably next week).

**Comment by alyhasansakr** [comment]
One of the things we need to do is to differentiate between configuration and making modules. Configuration is about getting the data from a configuration file, which is then passed to the module factory and the module connector.

The module factory takes in a json representation of a module definition (as in configuration file) and instantiate the correct type of module (selects subclass). Then calls initialization function of the module, which reads the rest of the json and sets specific module variables.

The module connector receives a json representation of a connection (as in configuration file) and searches for the mentioned modules and connect them (using a function in module).

Both module factory and module connector resides in module manager along with the list of modules. Module manager is a singleton and should contain minimal implementations (sort of a wrapper for module factory and module connector).

**Comment by alyhasansakr** [comment]
Each module should have a running state as well as its own state (basically, its instance variables). The module running state can be either paused or running. When running all input runners are also running, when paused, all input runners are also paused and output functions throws an exception "module is paused". The module should always keep its state when it is paused (unless it depends on external factors like real time).
The module state should be copyable (to another module of a compatible type), printable to a file, and readable from a file.
All modules should have a debug input exactly the same way we do it now but write it in its own class (and add it to the base module class).

**Comment by alyhasansakr** [comment]
Each module should have its own folder, package and tests. Writing a new module should involve minimal modification to any class outside this folder (I believe it should be only one line in module factory).

Each module should have its own documentation (javadoc) as well as its own wiki page (reference and example).

**Comment by alyhasansakr** [comment]
One more important point about exceptions allover the code: Different exceptions must have a different type, and must have a super type that is specific to each module (match-maker exception are a good example of that). You may also create other subtypes as necessary. This needs to apply to infrastructure manager exceptions as well (basically rewrite all exceptions).

As a rule, module exceptions should be throw up to a module input and be handled there (normal exceptions could be handled anywhere). Exceptions represents the only dependency between different types of modules (try to keep it minimal).

**Comment by alyhasansakr** [comment]
Just to clarify, you will need to revisit all of the implementations that we have and make sure that all of these rules apply. You may change them as necessary (including restructuring). You may need to write comments or documentation for the ones that are lacking. You may need to rewrite all of the tests that we have. And of course you need to move the files into their own folders (please use a refactoring tool for this, just like the one in IntelliJ).

The only part that you should not change is the application.

**Comment by alyhasansakr** [comment]
It is now ready for development.
