### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by juan-castrillon** [EdgeLab-FHDO/Edge-Diagnostic-Platform#76]
Given the new REST functionality, update the wiki so the platform can be used by external users

**Comment by juan-castrillon** [comment]
Should this wait for the modules refactor? Or better do it now and then again when modules are done? @alyhasansakr

**Comment by alyhasansakr** [comment]
@juan-castrillon Now is better.

**Comment by juan-castrillon** [comment]
In my last refactor, the platform is now automatically running all runners according to what is declared in the configuration file. I I did it mostly because of convienence to me while testing the functionalities but also because makes sense for the process to be as transparent as possible to the users. Should I reflect this in the new tutorials? Or do we still (for now) keep the need for the user to start each runner?

**Comment by alyhasansakr** [comment]
This was one of the points I wanted to solve with the modules. Basically, I would like to add a parameter "autostart" that does exactly that. For now just write mention your changes in the tutorial.

**Comment by juan-castrillon** [comment]
Ok, the changes to the wiki were:
- Modified "Using the platform" so the new option to run the master with a custom config file as parameter is included
- Modified the input types to account for the new `GenericPOST` and `NodeResourceLimiter` as well as deleting the old `RestInput`
- Added new page on how to configure the `GenericPOST` input
- Modified the output types to account for the new `GenericGET` and `NodeResourceLimiter` as well as deleting the old `RestOutput`
- Modified the REST API page
- Redid both MatchMaking and NodeLimit tutorials accounting for new types of inputs and outputs as well as autostart currently present in the platform (commented and ~~strikethrough~~ in some parts in order to be able to change it when we implement autostart as an option)

@alyhasansakr Have a look when you have time, and if you think is ok, go ahead and close the issue

**Comment by alyhasansakr** [comment]
That is very good.
