### ISSUE TITLE
Different Repositories

### ISSUE THREAD

**Issue by juan-castrillon** [EdgeLab-FHDO/Edge-Diagnostic-Platform#8]
Hey Ali

Wouldn't it be better to have separate repositories for the Diagnostics Platform and the Latency Measurement projects? 

Given that we are different people working on them and also I think that way, commits would be easier and also, the issues and the wiki can be just the ones for the specific project and not mixed. What do you think?

**Comment by alyhasansakr** [comment]
yes, you are right, looks like GitHub doesn't provide this level of isolation on project level, I will move it.

**Comment by alyhasansakr** [comment]
I think I have moved everything to the other repo at https://github.com/EdgeLab-FHDO/Latency-Measurement
