### ISSUE TITLE
Scenario module issue

### ISSUE THREAD

**Issue by zero212** [EdgeLab-FHDO/Edge-Diagnostic-Platform#82]
If this name in the config file
![image](https://user-images.githubusercontent.com/31235907/106143845-a4dcd000-6173-11eb-9741-73db331a8b4d.png)

Does not match this name (in the scenario file itself)
![image](https://user-images.githubusercontent.com/31235907/106143913-b9b96380-6173-11eb-8cd2-0ed05868cdba.png)

Module connector will throw the error.

**Comment by zero212** [comment]
@juan-castrillon 
T__T need help

**Comment by juan-castrillon** [comment]
Hey @zero212, can you show me the exception?

**Comment by juan-castrillon** [comment]
@zero212  Ok, I now  know what you mean. That was my idea though, that the scenario module (given that corresponds to a scenario) would have to have the same name as the scenario. So as long as that is true, it will work. However, I might have been wrong in assuming that was the correct thing to do...can you think of a use case where it would be different?

**Comment by alyhasansakr** [comment]
@juan-castrillon it is not about a certain use case. It is about when someone makes a mistake (like zero today), there is no way to know that this is the cause unless you look in the code. There should be one source for the scenario name, or one of them should override the other. Generating an exception randomly is not a good solution.

**Comment by juan-castrillon** [comment]
Yes you are right of course, but before adding that I was asking to see if that should always be the case (enforce the same name) or if there was a case I haven't considered in which that would not be desired. 

But, it should explicitly let someone know, you are right
