### ISSUE TITLE
Error when run the application

### ISSUE THREAD

**Issue by zero212** [EdgeLab-FHDO/Edge-Diagnostic-Platform#87]
Current master branch return error when runs application (no files were modified)

Here is the screenshot.

![image](https://user-images.githubusercontent.com/31235907/107342080-109e3180-6ac0-11eb-8ab5-ae7a077ab72b.png)

Am I being dump for not knowing something again or is it really not working...Would you mind have a look at it @juan-castrillon? 

Thanks buddy <3

**Comment by juan-castrillon** [comment]
I will have a look 🤔 But did you just run it normally?
```
.\gradle --console=plain run
```
 Otherwise @zero212 please tell how  so i can recreate this

**Comment by juan-castrillon** [comment]
nevermind, I just saw the error. I kinda messed up and forgot to add the output names 🤦 . I will make a pull request

**Comment by zero212** [comment]
Well, I double click this with Intelj, i'm not using Linux so :)). 

![image](https://user-images.githubusercontent.com/31235907/107345012-6b855800-6ac3-11eb-9841-1ce1f8013edc.png)
